[package]
name = "parser"
version = "0.1.0"
authors = ["Kaylynn <mkaylynn7@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
visitor_derive = { path = "visitor-derive" }
lasso = "0.6.0"
lexer = { path = "../lexer" }
logos = "0.12.0"
