[package]
name = "parser"
version = "0.1.0"
authors = ["Kaylynn <mkaylynn7@gmail.com>"]
edition = "2018"

[dependencies]
codegen = { path = "codegen" }
derive_more = "0.99.0"
lasso = "0.6.0"
lexer = { path = "../lexer" }
logos = "0.12.0"
